### ISSUE TITLE
The semicolon is not explained as a command separator

### ISSUE THREAD

**Issue by LaurentDardenne** [Jawz84/explainpowershell#80]
With :
```Powershell
Dir;Cls
```
The presence of the comma is missing from the explanation.

**Comment by Jawz84** [comment]
Good catch! I didn't even realize this was missing.
It is also an interesting one, as the line separator is not part of the AST, where all explanations are handled. It is handled by the tokenizer. The result of the tokenizer is the basis for the AST, but since explanations are only generated by walking the AST, the `;` sign does not get an explanation at this time. 
I agree this needs to be fixed.
