### ISSUE TITLE
[Feature] Specify if a language instruction is specific to a Powershell version.

### ISSUE THREAD

**Issue by LaurentDardenne** [Jawz84/explainpowershell#86]
Some language instructions are only specific from a certain version (range operator for characters, chaining operator, null coalescing, ...)
This is an information to know I think.

**Comment by LaurentDardenne** [comment]
Example  ( Workflow Test-Runbook {    'Commands' } ): 
![image](https://user-images.githubusercontent.com/4894452/176937455-9209fb0a-ee54-4b2b-a1fd-181fa7caa31e.png)

**Comment by Jawz84** [comment]
See also #85 - we could add a remark about the version in the .csv file?

About `workflow` the error that you see there is the actual parser error that is generated in trying to generate the AST, because the engine in ExplainPowerShell is 7.2.4 at this moment.
I also think that the explanation is lacking because the `function` keyword also does not have code to explain it yet.
We could handle the case of a workflow there, I think.

**Comment by LaurentDardenne** [comment]
_>>we could add a remark about the version in the .csv file?_
I don't know the code, hard to say.

I was thinking more about annotating new AST classes.

For the keyword 'Workflow' it was more information on the behavior of the website.
On the web page you can also specify something like this:
_ExplainPowerShell support all syntax up to version 7.2.4_
