### ISSUE TITLE
Process block inside a function is not explained

### ISSUE THREAD

**Issue by LaurentDardenne** [Jawz84/explainpowershell#89]
With 
```powershell
Function Expand-zipFile2 { param( )  Begin {1} Process{2} End{3}}
```
![image](https://user-images.githubusercontent.com/4894452/176937844-99efd6d5-4052-444b-aff8-3bfd185719b7.png)

**Comment by Jawz84** [comment]
The `function` keyword does not have an explanation in code yet, and I consciously mute explanation of named blocks, because the greatly clobber any normal explanation, because by default every scriptblock (the starting point of all epxlanations) is by defenition an EndBlock unless specified otherwise etc. 

We could add a special situation where named blocks are shown when their parent is a function keyword.
